pretrained_base_model_path: './model_weights/sd-image-variations-diffusers'
pretrained_vae_path: './model_weights/sd-vae-ft-mse'
image_encoder_path: './model_weights/image_encoder'



denoising_unet_path: "./exp_output/stage1/denoising_unet-92400.pth"
reference_unet_path: "./exp_output/stage1/reference_unet-92400.pth"
pose_guider_path: "./exp_output/stage1/pose_guider-92400.pth"

motion_module_path: "./exp_output/stage2/motion_module-24372.pth"





inference_config: "./configs/inference_v2.yaml"
weight_dtype: 'fp16'



test_cases:
  "./assets/images/0.jpg":
    - "./assets/poses/align/img_0_video_0.mp4"  